# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_result',
            name='values',
        ),
        migrations.AddField(
            model_name='test_result',
            name='logPath',
            field=models.CharField(default=2017, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test_result',
            name='timeId',
            field=models.CharField(default=8888, max_length=100),
            preserve_default=False,
        ),
    ]
