# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20171121_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('testId', models.IntegerField()),
                ('time', models.IntegerField()),
                ('value_cold', models.CharField(max_length=30, null=True)),
                ('value_hot', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('testId', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('app_type', models.CharField(blank=True, max_length=32, null=True)),
                ('test_type', models.CharField(blank=True, max_length=32, null=True)),
                ('app_url', models.CharField(blank=True, max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, max_length=32, null=True)),
                ('app_packageName', models.CharField(blank=True, max_length=32, null=True)),
                ('device_name', models.CharField(blank=True, max_length=32, null=True)),
                ('device_version', models.CharField(blank=True, max_length=32, null=True)),
                ('time', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('testId', models.IntegerField()),
                ('log_url', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Test_Result',
        ),
    ]
